### ISSUE TITLE
Add Chinese CultureInfo

### ISSUE THREAD

**Issue by Jeffiy** [joaomatossilva/DateTimeExtensions#45]
I want to add Chinese CultureInfo, but I don't know how to do? Can you give me some advice? thanks.

**Comment by kappy** [comment]
Hi.. The Chinese culture is a little bit different from what this library can support right now. 

I see also on Wikipedia (https://en.wikipedia.org/wiki/Public_holidays_in_China) the government decide each year when the holidays will be?

I don't think I have the Lunar calendar as well.

For the multiple day holidays, you can refer to ar-SA culture on https://github.com/kappy/DateTimeExtensions/blob/master/DateTimeExtensions/WorkingDays/CultureStrategies/AR_SAHolidayStrategy.cs

It's not a easy task. The Chinese calendar is very difficult, at least for me, by not knowing in detail the mechanics.

**Comment by Jeffiy** [comment]
It's not decided by government, it's decided by Lunar calendar

**Comment by kappy** [comment]
I created a Chinese Holiday Strategy, based on https://en.wikipedia.org/wiki/Public_holidays_in_China

I could not really get a proper formula for calculating the Tomb-Sweeping Day because that was a solar based and not lunar based like the others. 
So I created a map and applied it some known date observances from 2014 to 2018.
It's not really ideal, but It served the purpose.

Can you validate after release 2.8 is out?

**Comment by Jeffiy** [comment]
Oops, my fault, the `VACATION SUGGESTIONS` has some mistakes, it's actually decided by government.

HOLIDAYS | VACATION SUGGESTIONS
------------ | -------------
New Year | 2016/1/1-2016/1/3
Spring Festival | 2016/2/7-2016/2/13
Tomb-Sweeping Day | 2016/4/2-2016/4/4
International Workers' day | 2016/4/30-2016/5/2
Dragon Boat Festival | 2016/6/9-2016/6/11
Mid-Autumn Festival | 2016/9/15-2016/9/17
National Day | 2016/10/1-2016/10/7

**Comment by kappy** [comment]
Well, the Vacation Suggestions of the sample website are just for "fun" they're just a blind measure of the least days you need to take off, to get the most of days off.

It seems that we forgot about Qingming. I'm going to add that one (by a static map, since it's also solar based) and close this issue. I don't know if I can support year per year Government deciding the days off.

My goal is at least to have the correct days calculated.

**Comment by kappy** [comment]
My confusion.. Qingming was already implemented as Tomb-Sweeping Day. So I guess we can close this issue.
