### ISSUE TITLE
Holidays FR

### ISSUE THREAD

**Issue by YDEFAY** [joaomatossilva/DateTimeExtensions#82]
Hi, thanks for your DateTimeExttensions !
It's usefull and work realy great.

There are 2 days you can fix for french culture : 
- August 15 is holiday (Assumption of Mary)
- December 26 is a specific holiday for some departments (just a few people doesn't work on this day)

So if you can add August 15 and remove December 26 your french holidays calendar becomes right.

Thank you in advance

**Comment by joaomatossilva** [comment]
Thanks. I just fixed it, it should be live on next release.

I did not removed the December 26, because since version 5.0 I do now support regions, and so I constrainted it only to Alsace and Lorraine regions only (based on https://en.wikipedia.org/wiki/Public_holidays_in_France)

Can you confirm it's all ok now?
