### ISSUE TITLE
Support for .NET Framework 3.5

### ISSUE THREAD

**Issue by attiqeurrehman** [joaomatossilva/DateTimeExtensions#83]
Hi,

First of all, a lovely library and it was exactly what I was looking for. I was wondering can you add support for .NET Framework 3.5 as well?

Thanks,
Attiqe

**Comment by joaomatossilva** [comment]
Hi. Sorry, didn't noticed the issue.

I think the lowest I could go without much assle would be to 4.0.

Unless I make an implementation of Lazy<T> myself. I'll make a few tests and see.

**Comment by attiqeurrehman** [comment]
Thanks for reply and I will looking forward to it.

**Comment by joaomatossilva** [comment]
I think I have rather bad news.
https://github.com/Microsoft/msbuild/issues/1333

The CLI from dotnet core doesn't support building to target 3.5. Since it is the base of the entire build process of this library, this means I can't support the 3.5 Framework.

The workaround for it, is that you should be able to pull the source, and build it, from the net35 branch.
Try it if you like.

Sorry if It doesn't help you much, but I can't be holding on to older framework version since it would compromise the future.

**Comment by attiqeurrehman** [comment]
No problem, Thanks for your efforts.
